---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/johnnybionic/spring-cloud-microservice
          searchPaths: config-data
        # unit tests
        native:
          searchLocations: classpath:test-repository/
server:
  port: 8001