spring:
  data:
    entry:
      one: hello
lucky-word: Rabbit's Foot
#lucky-word: horseshoe
another-word: daredevil
---
#ConfigurationProperties example
sample:
  firstWord: first
  second-word: second
  THIRD_WORD: third-changed
